type: pages
label:
  en: Posts
  de: Beiträge
template: post
layout: cards
size: large
search: true
flip: true
info: '<br>{{page.subheading}}<br><br>{{page.date}}'
image:
  field: featuredImage
  cover: true
  ratio: 16/9
