title: Layout page

columns:
  main:
    width: 3/4
    sections:
      fields:
        type: fields
        fields:
          layout: fields/layout
          addresses: fields/addresses
  sidebar:
    width: 1/4
    sections:
      common:
        type: fields
        fields:
          featuredImage: fields/featuredImage
      files: sections/files

