title: Post
num: date
columns:
  main:
    width: 2/3
    fields:
      subheading:
        extends: fields/text
        label:
            en: Subheading
            de: Unterüberschrift
      bodyContent: fields/bodyContent

  sidebar:
    width: 1/3
    sections:
      fields:
        type: fields
        fields:
          featuredImage: fields/featuredImage
          author: fields/author
          date: fields/date
          topics: fields/topics
      files: sections/files


