title: Topics

columns:
  main:
    width: 2/3
    sections:
      fields:
        type: fields
        fields:
          featuredImage: fields/featuredImage
  sidebar:
    width: 1/3
    sections:
      pages:
        type: pages
        label:
          en: Main topics
          de: Hauptthemen
        template: topic
      files: sections/files


